apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tomcatpod 
spec:
  replicas: 3 
  selector:
   matchLabels:
    app: tomcatpod 
  template:
    metadata: 
      labels:
        app: tomcatpod
    spec:
      containers:
      - name: tomcatpod
        image: inampudi2020dap/dockerk8pipeline:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: tomcatpod-svc 
  labels:
    app: tomcatpod 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: tomcatpod